spring:
  application:
    name: customFilterTest

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    root: INFO
    com.customFilterTest.filterlab: DEBUG